I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 38, in script
    zhenya "Хз"
Exception: Sayer 'zhenya' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 38, in script
    zhenya "Хз"
  File "C:\Users\Dima\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Dima\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'zhenya' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
PRAEKT 1.0
Fri Nov 10 17:42:36 2023
